name: Legacy Publish
on:
  workflow_dispatch:
jobs:
  legacy-publish:
    name: Legacy publish
    # Windows is required for some of the unit tests to run properly
    runs-on: windows-2019
    steps:
      - name: Checkout code   
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
        
      - name: Set up Node
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2.5.1
        with:
          node-version: '16'
          check-latest: true          
          registry-url: 'https://www.myget.org/F/ed-fi/npm/'

      - name: Install
        run: yarn install
      
      - name: Build
        run: yarn build

      - name: Publish
        run: yarn publish-all
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_MYGET_ACCESS_TOKEN }}
