name: Lint and Test
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: Run the build with tmate debugging enabled
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Node modules cache
        id: modules-cache
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 #v4.0.0
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.modules-cache.outputs.cache-hit != 'true' }}
        run: npm install

      - name: Linter
        run: npm run test:lint

  unit-tests:
    name: Unit Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Node modules cache
        id: modules-cache
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 #v4.0.0
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.modules-cache.outputs.cache-hit != 'true' }}
        run: npm install

      - name: Unit Tests
        run: npm run test:unit:ci
        env:
          JEST_JUNIT_OUTPUT_DIR: unit-tests

      # Enable tmate debugging if the input option was provided (cd )
      - name: Setup tmate session
        if: always() && inputs.debug_enabled == 'true'
        uses: mxschmitt/action-tmate@a283f9441d2d96eb62436dc46d7014f5d357ac22 # v3.17
        timeout-minutes: 10

      - name: Unit Test Report
        uses: EnricoMi/publish-unit-test-result-action@f355d34d53ad4e7f506f699478db2dd71da9de5f # v2.15.1
        if: success() || failure()
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_name: ${{ github.event.workflow_run.event }}
          files: |
            unit-tests/*.xml
            unit-tests/*.trx
            unit-tests/*.json

  sql-server-tests:
    name: SQL Server Tests
    needs: lint
    runs-on: ubuntu-latest
    env:
      SA_PASSWORD: abcdefgh1!
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: ${{ env.SA_PASSWORD }}
          ACCEPT_EULA: "Y"
          MSSQL_PID: "Express"
        ports:
          - 1433:1433
        options: "--name mssql"

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Node modules cache
        id: modules-cache
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 #v4.0.0
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.modules-cache.outputs.cache-hit != 'true' }}
        run: npm install

      - name: Create SQL Server Testing Database
        run: |
          docker exec -i mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${{ env.SA_PASSWORD }} -d master \
            -Q "CREATE DATABASE MetaEd_Ods_Integration_Tests"

      - name: SQLServer Unit tests
        run: npm run test:unit:ods:sqlserver:db -- --ci  --config ./jest.ci-config.js
        env:
          MSSQL_USERNAME: sa
          MSSQL_PASSWORD: ${{ env.SA_PASSWORD }}
          MSSQL_TRUST_CERTIFICATE: "true" # This is required for successful auth to the docker SQL Server
          JEST_JUNIT_OUTPUT_DIR: sqlserver-tests

      - name: SQLServer Test Report
        uses: EnricoMi/publish-unit-test-result-action@f355d34d53ad4e7f506f699478db2dd71da9de5f # v2.15.1
        if: success() || failure()
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_name: ${{ github.event.workflow_run.event }}
          files: |
            sqlserver-tests/*.xml
            sqlserver-tests/*.trx
            sqlserver-tests/*.json

  postgres-tests:
    name: PostgreSQL Tests
    needs: lint
    runs-on: ubuntu-latest
    env:
      SA_PASSWORD: abcdefgh1!
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Node modules cache
        id: modules-cache
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 #v4.0.0
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.modules-cache.outputs.cache-hit != 'true' }}
        run: npm install

      - name: Setup PostgreSQL for testing
        # Postgres on Ubuntu is installed locally but the service needs to be started. The default postgres
        # super user password is blank, so updating to what the unit tests expect, also creating the testing database
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres psql -U postgres -c "create database metaed_integration_tests;"
          sudo -u postgres psql -U postgres -c "alter user postgres with password 'docker';"

      - name: PostgreSQL Unit tests
        run: npm run test:unit:ods:postgresql:db -- --ci --config ./jest.ci-config.js
        env:
          JEST_JUNIT_OUTPUT_DIR: postgresql-tests

      - name: PostgreSQL Test Report
        uses: EnricoMi/publish-unit-test-result-action@f355d34d53ad4e7f506f699478db2dd71da9de5f # v2.15.1
        if: success() || failure()
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_name: ${{ github.event.workflow_run.event }}
          files: |
            postgresql-tests/*.xml
            postgresql-tests/*.trx
            postgresql-tests/*.json
