on:
  workflow_call:
jobs:
  reusable-lint-and-test:
    name: Reusable Lint and Test
    # Windows is required for some of the unit tests to run properly
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Set up Node
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2.5.1
        with:
          node-version: '16'
          check-latest: true
          registry-url: 'https://www.myget.org/F/ed-fi/npm/'

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn test:lint

      - name: Unit tests
        run: yarn test:unit:ci --ci  --config ./jest.ci-config.js

      - name: Test Report
        uses: dorny/test-reporter@0d00bb14cb0cc2c9b8985df6e81dd333188224e1 #v1.5.0
        if: success() || failure()
        with:
          name: Test Reporting
          path: "*.xml"
          reporter: jest-junit  